### ISSUE TITLE
Textures not rendered

### ISSUE THREAD

**Issue by DanThePman** [Vogtinator/nGL#1]
Hey,
Since today the next-branch works fine because previously quads haven't been rendered properly if their z distance to the camera was less than ~170.

But textures don't work for me.
A quad/triangle just changes to a single color instead of the complete texture.

Here's my glconfig:

```
//Colored triangles can still be used with nglForceColor(true)
#define TEXTURE_SUPPORT

//Warning, this is slower than textured rendering!
//#define INTERPOLATE_COLORS

//#define WIREFRAME_MODE

//If disabled, triangles partially behind the CLIP_PLANE will be discarded
#define Z_CLIPPING

//Deactivate after you don't get any warnings.
//Otherwise it may corrupt random memory and crash.
#define SAFE_MODE

//If some geometry inaccuracies annoy you, enable this.
//It's a bit slower though.
//#define BETTER_PERSPECTIVE

//Print "FPS: <fps>\n" to stdout every second
//#define FPS_COUNTER

#if defined(TEXTURE_SUPPORT) && defined(INTERPOLATE_COLORS)
#error "Colors and textures cannot be used simultaneously!"
#endif

#define CLIP_PLANE 25

#define MATRIX_STACK_SIZE 10
```

I also tried it with other options but it doesn't want to apply the texture.

**Comment by Vogtinator** [comment]
Hi, can I see a complete code example reproducing the bug?
I'm using the nGL/next branch to compile crafti/next and it works fine.

**Comment by DanThePman** [comment]
For me the code of tutorial 2 ends up with a single color.

Btw I'm using the firebird emulator with nspire cx cas OS v3.6.
Does the version maybe matter?

**Comment by Vogtinator** [comment]
It definitely shouldn't, I'll test it and find out what's going wrong here. How do you compile it (gcc version, etc.)?

**Comment by Vogtinator** [comment]
Just tried it, works fine here.

**Comment by DanThePman** [comment]
Im using gcc 5.3 on windows with
`GCCFLAGS = -Wall -W -marm -std=c++11` in the makefile.
Building with visual studio using the visualgdb extension as bridge for cygwin make.

**Comment by Vogtinator** [comment]
Can you upload your complete project?
I'll just run make and see if it works. If it does, it's somehow a bug in the toolchain.

**Comment by DanThePman** [comment]
While cloning the project I found (?) the issue.
Changing the name at`ZEHNFLAGS = --name "xyz"` and `EXE = xyz` made it work.
I have no plan why but it's working now.
The original Makefile I used was placed in the helloworld-cpp example.

Thanks anyway for your help and thanks for the lib
